"""The native library emitter: contracts -> a Python module.

Deliberately thin (ADR 0003): the generated file embeds the contracts as
data and wraps them in typed functions that call arkhelang.runtime. All
guard, authority, approval, effect, and audit semantics live in the runtime
and the contracts, never in generated code.
"""

from __future__ import annotations

import json


def _fn_name(contract_name: str) -> str:
    return contract_name.split(".", 1)[1]


def _param_doc(decl: dict) -> str:
    kind = decl["type"]
    if decl.get("values") is not None:
        kind += " (" + " | ".join(map(str, decl["values"])) + ")"
    if decl.get("optional"):
        kind += ", optional"
    if decl.get("synonyms"):
        kind += ", aka: " + ", ".join(decl["synonyms"])
    return kind


class EmitError(ValueError):
    """The module cannot be emitted as a coherent library."""


def _read_fn_name(entity: str) -> str:
    return "get_" + "".join(
        "_" + ch.lower() if ch.isupper() and i else ch.lower()
        for i, ch in enumerate(entity))


def emit(module_doc: dict, contracts: dict[str, dict]) -> str:
    """Generated Python source for the module's native library.

    All embedded text (contract JSON, descriptions) is escaped via repr, so
    module content can never break out of the generated source. The result
    is compile-checked before it is returned.
    """
    module_name = module_doc["module"]

    # One flat namespace: action names and read accessors must not collide.
    fn_names: dict[str, str] = {}
    for name, contract in sorted(contracts.items()):
        fn = (_fn_name(name) if contract["kind"] == "action"
              else _read_fn_name(contract["target"]["entity"].split(".", 1)[1]))
        if fn in fn_names:
            raise EmitError(
                f"generated function '{fn}' for {name} collides with "
                f"{fn_names[fn]}; rename the action or entity")
        fn_names[fn] = name

    lines: list[str] = []
    w = lines.append

    w('"""Generated by `arkhe emit --target=lib`. Do not edit.')
    w("")
    w(f"Native library for the {module_name!r} Arkhe module. Every function")
    w("enforces its tool contract: authority claims, CEL guard, approval")
    w("escalation, and audit, refusing with a structured reason otherwise.")
    w('"""')
    w("")
    w("import json")
    w("")
    w("from arkhelang.runtime import World, execute")
    w("")
    w(f"_CONTRACTS = json.loads({json.dumps(contracts, sort_keys=True)!r})")
    w("")
    w(f"_MODULE = json.loads({json.dumps(module_doc, sort_keys=True)!r})")
    w("")
    w("")
    w("def new_world() -> World:")
    w(f"    {'An empty in-memory world for the %s module.' % module_name!r}")
    w("    return World(module=_MODULE)")
    w("")

    for name, contract in sorted(contracts.items()):
        if contract["kind"] != "action":
            continue
        fn = _fn_name(name)
        key_arg = contract["target"]["keys"][0]
        params = dict(sorted(
            (contract.get("parameters") or {}).items(),
            key=lambda item: bool(item[1].get("optional"))))  # required first
        sig_params = "".join(
            f", {p}=None" if decl.get("optional") else f", {p}"
            for p, decl in params.items())
        w("")
        w(f"def {fn}(world, {key_arg}{sig_params}, *, actor, approver=None):")
        doc = contract.get("description") or f"Attempt {name}."
        synonyms = contract.get("synonyms")
        if synonyms:
            doc += "\n\nAlso known as: " + ", ".join(synonyms) + "."
        if params:
            doc += "\n\n" + "\n".join(
                f"{p}: {_param_doc(decl)}" for p, decl in params.items())
        w(f"    {doc!r}")
        if params:
            call_params = ", ".join(f'"{p}": {p}' for p in params)
            w(f"    params = {{{call_params}}}")
            w("    params = {k: v for k, v in params.items() if v is not None}")
        else:
            w("    params = {}")
        w(f'    return execute(_CONTRACTS["{name}"], world, {key_arg},')
        w("                   actor=actor, params=params, approver=approver)")
        w("")

    for name, contract in sorted(contracts.items()):
        if contract["kind"] != "read":
            continue
        entity = contract["target"]["entity"].split(".", 1)[1]
        fn = _read_fn_name(entity)
        key_arg = contract["target"]["keys"][0]
        w("")
        w(f"def {fn}(world, {key_arg}, depth=2):")
        doc = "Read one %s with traversals materialized to depth." % entity
        synonyms = contract.get("synonyms")
        if synonyms:
            doc += "\n\nAlso known as: " + ", ".join(synonyms) + "."
        w(f"    {doc!r}")
        w(f'    return world.neighbourhood("{entity}", {key_arg}, depth)')
        w("")

    source = "\n".join(lines) + "\n"
    try:
        compile(source, f"<emitted {module_name}_lib>", "exec")
    except SyntaxError as exc:  # pragma: no cover - the check is the point
        raise EmitError(f"emitted source does not compile: {exc}") from exc
    return source
